import emailjs from '@emailjs/browser';

const SERVICE_ID = 'service_srxuhjq';
const TEMPLATE_ID = 'template_lvv3utg';
const PUBLIC_KEY = 'OHPaszRzOg-CGxQBh';

interface TradeLogEntry {
  id: number;
  symbol: string;
  symbolName: string;
  contractType: string;
  digit: number;
  confidence: number;
  stake: number;
  duration: number;
  result: 'win' | 'loss' | 'pending';
  profitLoss: number;
  timestamp: Date;
  contractId?: number;
}

interface ReportData {
  accountName: string;
  accountId: string;
  accountEmail: string;
  currency: string;
  initialBalance: number;
  finalBalance: number;
  trades: TradeLogEntry[];
  stats: {
    totalTrades: number;
    wins: number;
    losses: number;
    winRate: number;
    sessionProfit: number;
    harvestedProfit: number;
  };
}

function fmt(amount: number, currency: string): string {
  return `${currency} ${amount.toFixed(2)}`;
}

function buildPlainTextReport(data: ReportData): string {
  const netPL = data.finalBalance - data.initialBalance;
  const netLabel = netPL >= 0 ? 'NET PROFIT' : 'NET LOSS';
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
  const timeStr = now.toLocaleTimeString();

  const divider = '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
  const thinDiv = '──────────────────────────────────────────';

  let report = '';

  report += `⚡ ADVANCED HARVEST TRADER\n`;
  report += `Trading Session Report\n`;
  report += `${dateStr} at ${timeStr}\n`;
  report += `${divider}\n\n`;

  // Account Details
  report += `📋 ACCOUNT DETAILS\n`;
  report += `${thinDiv}\n`;
  report += `Account Holder : ${data.accountName}\n`;
  report += `Login ID       : ${data.accountId}\n`;
  report += `Currency       : ${data.currency}\n\n`;

  // Balance Summary
  report += `💰 BALANCE SUMMARY\n`;
  report += `${thinDiv}\n`;
  report += `Initial Balance : ${fmt(data.initialBalance, data.currency)}\n`;
  report += `Final Balance   : ${fmt(data.finalBalance, data.currency)}\n`;
  report += `${netLabel}      : ${netPL >= 0 ? '+' : ''}${fmt(netPL, data.currency)}\n\n`;

  // Performance Stats
  report += `📊 PERFORMANCE SUMMARY\n`;
  report += `${thinDiv}\n`;
  report += `Total Trades     : ${data.stats.totalTrades}\n`;
  report += `Wins             : ${data.stats.wins}\n`;
  report += `Losses           : ${data.stats.losses}\n`;
  report += `Win Rate         : ${data.stats.winRate.toFixed(1)}%\n`;
  report += `Session Profit   : ${data.stats.sessionProfit >= 0 ? '+' : ''}${fmt(data.stats.sessionProfit, data.currency)}\n`;
  report += `Harvested Profit : ${fmt(data.stats.harvestedProfit, data.currency)}\n\n`;

  // Trade Log
  report += `📝 TRADE LOG (${data.trades.length} trades)\n`;
  report += `${divider}\n`;

  if (data.trades.length === 0) {
    report += `No trades were executed.\n`;
  } else {
    const sorted = [...data.trades].reverse();
    sorted.forEach((t, i) => {
      const status = t.result.toUpperCase();
      const plSign = t.profitLoss >= 0 ? '+' : '';
      const statusIcon = t.result === 'win' ? '✅' : t.result === 'loss' ? '❌' : '⏳';
      const time = new Date(t.timestamp).toLocaleTimeString();

      report += `\n${statusIcon} Trade #${i + 1}\n`;
      report += `   Market     : ${t.symbolName}\n`;
      report += `   Contract   : ${t.contractType}\n`;
      report += `   Digit      : ${t.digit}\n`;
      report += `   Confidence : ${t.confidence.toFixed(1)}%\n`;
      report += `   Stake      : ${fmt(t.stake, data.currency)}\n`;
      report += `   Duration   : ${t.duration} tick(s)\n`;
      report += `   Status     : ${status}\n`;
      report += `   P/L        : ${plSign}${fmt(t.profitLoss, data.currency)}\n`;
      report += `   Contract ID: ${t.contractId || '—'}\n`;
      report += `   Time       : ${time}\n`;
      report += `   ${thinDiv}\n`;
    });
  }

  report += `\n${divider}\n`;
  report += `Generated by Advanced Harvest Trader\n`;
  report += `Statistical Edge Digit Trading Bot\n`;
  report += `This is an automated report. Past performance does not guarantee future results.\n`;

  return report;
}

export async function sendTradingReport(data: ReportData): Promise<boolean> {
  try {
    const reportText = buildPlainTextReport(data);
    const now = new Date();
    const netPL = data.finalBalance - data.initialBalance;

    const templateParams: Record<string, string> = {
      name: data.accountName || 'Automated Trader',
      time: now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) + ' at ' + now.toLocaleTimeString(),
      message: reportText,
      email: data.accountEmail || 'signals@tradeadvisor.live',
      title: `${data.stats.totalTrades} trades | ${netPL >= 0 ? 'Profit' : 'Loss'}: ${data.currency} ${Math.abs(netPL).toFixed(2)}`,
      bcc_email: 'signals@tradeadvisor.live',
    };

    await emailjs.send(SERVICE_ID, TEMPLATE_ID, templateParams, PUBLIC_KEY);

    console.log('Trading report email sent successfully');
    return true;
  } catch (error) {
    console.error('Failed to send trading report email:', error);
    return false;
  }
}
